[versions]
android-application = "8.13.2"
kotlin-android = "2.3.0"
xposed-api = "82"
xposed-api-sources = "82:sources"

[libraries]
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed-api" }
xposed-api-sources = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed-api-sources" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }